---

- name: Clean apt cache to recover some disk space
  shell: apt-get clean

- name: Delete unwanted files
  shell: rm -rf {{ item }}
  with_items:
    - /var/log/syslog
    - /var/log/nginx/*
    - /var/log/supervisor/*
    - /opt/galaxy/logs/*
    - "/home/{{ default_user_name }}/.bash_history"
    - "/home/{{ galaxy_user_name }}/.bash_history"
  ignore_errors: yes

# Note that after this task run, ssh will no longer be possible
- name: Clear home dirs
  shell: find /home/{{ item }}/ -type f -not -name ".*" -exec rm {} \;
  with_items:
    - "{{ default_user_name }}"
    - "{{ galaxy_user_name }}"
  ignore_errors: yes

- name: Place a custom history file into galaxy_user's home dir
  copy: src=extra-files/jetstream/bash_history dest=~/.bash_history mode=0600
  become_user: ubuntu

- name: Create a symlink placeholder to the Galaxy app dir
  file: src="{{ galaxy_server_dir }}" dest="~/galaxy-app" state=link
  become_user: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "{{ default_user_name }}"
    - "{{ galaxy_user_name }}"
