---

- name: Assure galaxyFS dir exists
  file: path={{ galaxyFS_base_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Create shed tools dir
  file: state=directory path={{ galaxy_shed_tools_dir }} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Create database dir
  file: path={{ galaxy_database }} state=directory owner=postgres group=postgres

- name: Install samtools system package
  apt: pkg=samtools state=present

- name:  Copy fix_hostname script
  copy: src=extra-files/jetstream/fix_hostname.sh dest=/usr/local/bin/fix_hostname.sh mode=0755

- name: Add fix_hostname script to /etc/rc.local
  lineinfile: dest=/etc/rc.local line='/usr/local/bin/fix_hostname.sh' insertbefore="exit 0"

- name: Ensure galaxy log dir exists
  file: path={{ galaxy_log_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Setup /etc/bash.bashrc
  lineinfile: dest=/etc/bash.bashrc line="{{ item }}"
  with_items:
    - "alias 'lt=ls -ltr'"
    - "alias 'll=ls -l'"

- name: Restart hostname service
  shell: service hostname restart

- shell: "hostname"
  register: hostname

- name: Fix /etc/hosts on running instance
  replace: dest=/etc/hosts regexp='127.0.0.1 localhost$' replace='127.0.0.1 localhost {{ hostname.stdout }}'
