---

- name: Assure galaxyFS dir exists
  file: path={{ galaxyFS_base_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Ensure galaxyFS log dir exists
  file: path={{ galaxy_log_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Setup /etc/bash.bashrc
  lineinfile: dest=/etc/bash.bashrc line="{{ item }}"
  with_items:
    - "alias 'lt=ls -ltr'"
    - "alias 'll=ls -l'"
    - "sh /etc/init.d/fix_hostname.sh > /dev/null 2>&1"

- name:  Copy fix_hostname script
  copy: src=extra-files/jetstream/fix_hostname.sh dest=/etc/init.d/fix_hostname.sh mode=0755

# Install & setup CermVM-FS for reference data
- include: cvmfs_client.yml
