---

- name: Assure galaxyFS dir exists
  file: path={{ galaxyFS_base_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Create shed tools dir
  file: state=directory path={{ galaxy_shed_tools_dir }} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Create database dir
  file: path={{ galaxy_database }} state=directory owner=postgres group=postgres

- name: Install samtools system package
  apt: pkg=samtools state=present

- name:  Copy fix_hostname script
  copy: src=extra-files/jetstream/fix_hostname.sh dest=/usr/local/bin/fix_hostname.sh mode=0755

- name: Add fix_hostname script to /etc/rc.local
  lineinfile: dest=/etc/rc.local line='/usr/local/bin/fix_hostname.sh' insertbefore="exit 0"

- name: Ensure galaxy log dir exists
  file: path={{ galaxy_log_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Setup /etc/bash.bashrc
  lineinfile: dest=/etc/bash.bashrc line="{{ item }}"
  with_items:
    - "alias 'lt=ls -ltr'"
    - "alias 'll=ls -l'"

- name: Restart hostname service
  service:
    name: hostname
    state: restarted

- shell: "hostname"
  register: hostname

- name: Fix /etc/hosts on running instance
  replace: dest=/etc/hosts regexp='127.0.0.1 localhost$' replace='127.0.0.1 localhost {{ hostname.stdout }}'  #'

# Install & setup CermVM-FS
- name: Download cvmfs
  get_url:
    url="{{ cvmfs_deb_url }}"
    dest="/tmp/cvmfs.deb"

- name: Download cvmfs-config
  get_url:
    url="{{ cvmfs_deb_config_url }}"
    dest="/tmp/cvmfs-config.deb"

- name: Install cvmfs-config
  apt: deb="/tmp/cvmfs-config.deb"

- name: Install cvmfs
  apt: deb="/tmp/cvmfs.deb"

- name: Install CernVM-FS keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "0444"
  with_items: "{{ cvmfs_keys }}"

- name: Perform AutoFS and FUSE configuration for CernVM-FS
  command: cvmfs_config setup
  notify:
    - restart autofs

- name: Configure CernVM-FS domain
  copy:
    content: |
      CVMFS_SERVER_URL="{{ item.urls | join(';') }}"
    dest: "/etc/cvmfs/domain.d/{{ item.domain }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ cvmfs_server_urls }}"

- name: Configure CernVM-FS repositories and proxy
  copy:
    content: |
      CVMFS_REPOSITORIES="{{ cvmfs_repositories | join(',') }}"
      CVMFS_HTTP_PROXY="{{ cvmfs_http_proxies | join('|') }}"
    dest: "/etc/cvmfs/default.local"
    owner: "root"
    group: "root"
    mode: "0644"
