# By default, everything lives in the Galaxy clone
    galaxy_config_dir: "{{ galaxy_data }}/config"
    galaxy_mutable_config_dir: "{{ galaxy_data }}/config"
    galaxy_mutable_data_dir: "{{ galaxy_data }}/database"

    galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
    galaxy_shed_tool_conf_file: "{{ galaxy_mutable_config_dir }}/shed_tool_conf.xml"

    builds_file_path: "{{ galaxy_data }}/tool-data/shared/ucsc/builds.txt.sample"
    data_manager_config_file: "{{ galaxy_data }}/config/data_manager_conf.xml.sample"
    datatypes_config_file: "{{ galaxy_data }}/config/datatypes_conf.xml.sample"
    external_service_type_config_file: "{{ galaxy_data }}/config/external_service_types_conf.xml.sample"
    openid_config_file: "{{ galaxy_data }}/config/openid_conf.xml.sample"
    tool_config_file: "{{ galaxy_data }}/config/tool_conf.xml.sample,{{ galaxy_shed_tool_conf_file }}"
    tool_sheds_config_file: "{{ galaxy_data }}/config/tool_sheds_conf.xml.sample"
    ucsc_build_sites: "{{ galaxy_data }}/tool-data/shared/ucsc/ucsc_build_sites.txt.sample"
    tool_data_table_config_path: "{{ galaxy_data }}/config/tool_data_table_conf.xml.sample"
    visualization_plugins_directory: "{{ galaxy_data }}/config/plugins/visualizations"

    integrated_tool_panel_config: "{{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml"
    migrated_tools_config: "{{ galaxy_mutable_config_dir }}/migrated_tools_conf.xml"
    shed_data_manager_config_file: "{{ galaxy_mutable_config_dir }}/shed_data_manager_conf.xml"
    shed_tool_data_table_config: "{{ galaxy_mutable_config_dir }}/shed_tool_data_table_conf.xml"
    file_path: "{{ galaxy_mutable_data_dir }}/datasets"
    new_file_path: "{{ galaxy_mutable_data_dir }}/tmp"
    job_working_directory: "{{ galaxy_mutable_data_dir }}/jobs"
    template_cache_path: "{{ galaxy_mutable_data_dir }}/template_cache"
    whoosh_index_dir: "{{ galaxy_mutable_data_dir }}/whoosh_cache"
    object_store_cache_path: "{{ galaxy_mutable_data_dir }}/object_store_cache"
    openid_consumer_cache_path: "{{ galaxy_mutable_data_dir }}/openid_consumer_cache"
    citation_cache_data_dir: "{{ galaxy_mutable_data_dir }}/citations/data"
    citation_cache_lock_dir: "{{ galaxy_mutable_data_dir }}/citations/locks"

    
    
        #installs galaxy
    - role: galaxyprojectdotorg.galaxy
      #persistent data
      galaxy_manage_mutable_setup: yes
      galaxy_mutable_config_dir: "{{ galaxy_config_dir }}"
#      galaxy_shed_tool_conf_file: "{{ galaxy_mutable_config_dir }}/shed_tool_conf.xml"
#      visualization_plugins_directory: "{{ galaxy_data }}/config/plugins/visualizations"
      #other vars
      galaxy_manage_database: yes
      galaxy_fetch_eggs: no
      galaxy_changeset_id: master
      galaxy_vcs: git
      galaxy_venv_dir: "{{ galaxy_venv }}"
      galaxy_server_dir: "{{ galaxy_dir }}"
      galaxy_config:
        "app:main":
          admin_users: "{{ galaxy_admin }}"
          database_connection: "{{ galaxy_db }}"
          tool_dependency_dir: "{{ galaxy_data }}/lib/tool_shed/dependencies"
          master_api_key: "{{ galaxy_api }}"
          ftp_upload_dir: "{{ galaxy_ftp }}" 
          ftp_upload_site: "ftp {{ galaxy_hostname }} port {{ ftp_port }}"
          #to be done only in production       
          #debug: False
          #use_interactive: False
          nginx_x_accel_redirect_base: "/_x_accel_redirect"
          nginx_x_archive_files_base: "/_x_accel_redirect"
          nginx_upload_store: "/tmp"
          nginx_upload_path: "/_upload"
          welcome_url: "/static/welcome.html"
          #persistent data
#          data_manager_config_file: "{{ galaxy_data }}/config/data_manager_conf.xml.sample"
#          external_service_type_config_file: "{{ galaxy_data }}/config/external_service_types_conf.xml.sample"
#          tool_config_file: "{{ galaxy_data }}/config/tool_conf.xml.sample,{{ galaxy_shed_tool_conf_file }}"
#          tool_data_table_config_path: "{{ galaxy_data }}/config/tool_data_table_conf.xml.sample"
#          tool_sheds_config_file: "{{ galaxy_data }}/config/tool_sheds_conf.xml.sample"
#          datatypes_config_file: "{{ galaxy_data }}/config/datatypes_conf.xml.sample"
#          openid_config_file: "{{ galaxy_data }}/config/openid_conf.xml.sample"
#          ucsc_build_sites: "{{ galaxy_data }}/tool-data/shared/ucsc/ucsc_build_sites.txt.sample"
#          builds_file_path: "{{ galaxy_data }}/tool-data/shared/ucsc/builds.txt.sample"
    