- hosts: all
#  remote_user: root
  sudo: yes

  vars:
    #Globals
    galaxy_data: "/galaxy_data"
    galaxy_hostname: "localhost"
    galaxy_user: "galaxy"
    galaxy_port: "8080"
    ftp_port: "21"
    galaxy_host: "0.0.0.0"
    galaxy_user_uid: 1005 # Used by galaxy role and proftpd include
    galaxy_admin: "artimed@gmail.com"
    galaxy_dir: "/home/{{ galaxy_user }}/{{ galaxy_user }}"
    galaxy_venv: "{{ galaxy_dir }}/.venv" # Used by galaxy and galaxy-extras roles
    galaxy_ftp: "{{ galaxy_dir }}/database/ftp"
    galaxy_api: 379ab2a47d714a74b5cee4081703368e
    galaxy_db: "postgresql:///{{ galaxy_user }}?host=/var/run/postgresql"
    galaxy_ftp: "{{ galaxy_dir }}/database/ftp"

  roles:
    #installs system package requirements
    - role: galaxyprojectdotorg.galaxy-os
      configure_docker: no
      galaxy_user_name: "{{ galaxy_user }}"

    #this role included in galaxyprojectdotorg.galaxy as a submodule to create galaxy user and its db 
    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user }}"
          password: "{{ galaxy_user }}"
      postgresql_objects_databases:
        - name: "{{ galaxy_user }}"
          owner: "{{ galaxy_user }}"
      sudo: yes
      sudo_user: postgres

    #installs galaxy
    - role: galaxyprojectdotorg.galaxy
      #galaxy_manage_clone: no
      galaxy_manage_database: yes
      galaxy_fetch_eggs: no
      galaxy_changeset_id: master
      galaxy_vcs: git
      galaxy_venv_dir: "{{ galaxy_venv }}"
      galaxy_server_dir: "{{ galaxy_dir }}"
      galaxy_config_dir: "{{ galaxy_dir }}/config"
      galaxy_mutable_config_dir: "{{ galaxy_config_dir }}"
      galaxy_config:
        "app:main":
          admin_users: "{{ galaxy_admin }}"
          database_connection: "{{ galaxy_db }}"
          tool_dependency_dir: "{{ galaxy_dir }}/lib/tool_shed/dependencies"
          master_api_key: "{{ galaxy_api }}"
          ftp_upload_dir: "{{ galaxy_ftp }}" 
          ftp_upload_site: "ftp {{ galaxy_hostname }} port {{ ftp_port }}"
          #to be done only in production       
          #debug: False
          #use_interactive: False
          nginx_x_accel_redirect_base: "/_x_accel_redirect"
          nginx_x_archive_files_base: "/_x_accel_redirect"
          nginx_upload_store: "/tmp"
          nginx_upload_path: "/_upload"
        "uwsgi":
          stats: "{{ galaxy_hostname }}:9191"
          socket: "{{ galaxy_hostname }}:4001"
          master: True
          logto: "{{ galaxy_dir }}/uwsgi.log"
          pythonpath: lib
          threads: 4
          processes: "{{ galaxy_web_processes }}"
      sudo: yes
      sudo_user: "{{ galaxy_user }}"

    #installs nginx and proftpd
    - role: galaxyprojectdotorg.galaxy-extras
      galaxy_root: "{{ galaxy_dir }}"
      galaxy_log_dir: "{{ galaxy_dir }}"
      galaxy_venv_dir:  "{{ galaxy_venv }}"
      galaxy_database_connection: "{{ galaxy_db }}"
      galaxy_extras_install_packages: true
      galaxy_extras_config_nginx: true
      galaxy_extras_config_supervisor: true
      galaxy_extras_config_proftpd: true
      galaxy_extras_config_uwsgi: true
      galaxy_extras_config_galaxy_job_metrics: true
      galaxy_extras_config_slurm: true
      galaxy_extras_config_galaxy_root: true
      galaxy_extras_config_ie_proxy: false
      supervisor_manage_postgres: false
      supervisor_manage_nginx: true
      supervisor_manage_proftp: true
      supervisor_manage_slurm: true
      supervisor_manage_reports: true
      supervisor_manage_docker: false
      supervisor_manage_nodeproxy: false
      supervisor_manage_ie_proxy: false      

  tasks:
    - service: name=supervisor state=restarted
    - include: roles/artimed_extra/files/proftpd.yml
