- hosts: all
  become: yes
  gather_facts: yes

  environment: "{{ proxy_env }}"

  handlers:
    - include_tasks: roles/handlers/galaxy.yml

  pre_tasks:
    - name: Check ansible version
      fail: msg="Installed ansible version {{ ansible_version.full }}, but ansible version >= 2.7.4 required"
      when: ansible_version.full is version('2.7', '<')
      tags:
        - always

    - name: Install python if absent
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout
      tags:
        - always

    - name: gather facts
      setup:
      tags:
        - always

    - name: set jetstream banner image variable
      set_fact:
        banner_img: "{% if 'jetstream' in group_names %}jetstream_text.png{% else %}gce_text.png{% endif %}"

    - name: get host ip in ipify_public_ip variable
      ipify_facts:
        timeout: 20
      tags:
        - always

  roles:

    - role: galaxyprojectdotorg.galaxy-os
      tags:
        - install_galaxy
        - install_packages

    - role: cloud_setup
      when: cloud_setup is defined

    - role: ensure_postgresql_up
      tags:
        - install_galaxy
        - manage_postgres

    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user_name }}"
          password: "{{ galaxy_user_name }}"
          encrypted: "yes"
      postgresql_objects_databases:
        - name: "{{ galaxy_user_name }}"
          owner: "{{ galaxy_user_name }}"
      become: yes
      become_user: postgres
      tags:
        - install_galaxy
        - manage_postgres

    - role: galaxyprojectdotorg.galaxy
      become: yes
      become_user: "{{ galaxy_user_name }}"
      tags:
        - configure_galaxy
        - install_galaxy
      vars:
        - ansible_check_mode: no # test tests


    - role: set_supervisor_env_vars
      tags: env_vars

    # The return of miniconda !
    - role: miniconda-role
      become: yes
      become_user: "{{ galaxy_user_name }}"
      tags: conda

    # Installs supervisor, nginx and proftpd
    - role: galaxyprojectdotorg.galaxy-extras
      tags:
        - configure_server_stack
        - install_extras

    - role: ensure_postgresql_up
      tags:
        - manage_postgres
        - install_tools

    - role: copy_additional_files
      tags:
        - install_extras

    - role: galaxy.movedata
      tags:
        - persists_galaxy

    - role: galaxyprojectdotorg.trackster
      tags: configure_galaxy

  post_tasks:

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
