- hosts: all
  sudo: yes

  vars:
    #params
    galaxy_hostname: "{{ INSTALL_HOSTNAME|default('localhost') }}" #next upgrade: automaticlly dicovers the public ip
    galaxy_user: "{{ GALAXY_USER|default('galaxy') }}" 
    galaxy_dir: "{{ GALAXY_DIR|default('/home/galaxy/galaxy') }}" 
    galaxy_admin: "{{ GALAXY_ADMIN|default('artimed@gmail.com') }}"
    ftp_port: "{{ FTP_PORT|default('21') }}"
    galaxy_api: "{{ GALAXY_KEY|default('379ab2a47d714a74b5cee4081703368e') }}"
    install_galaxy: "{{ INSTALL_GALAXY|default('True') }}"
    install_tools: "{{ INSTALL_TOOLS|default('False') }}"
    galaxy_tools: "{{ GALAXY_TOOLS|default('roles/artimed_extras/files/artimed_tool_list.yaml') }}"
    #persistent params
    galaxy_data: "{{ GALAXY_DATA|default('/home/galaxy/galaxy') }}"
    galaxy_database: "{{ GALAXY_DATABASE|default('/home/galaxy_database') }}"
    galaxy_db: "{{ GALAXY_DB_CONN|default('postgresql:///{{ galaxy_user }}?host=/var/run/postgresql') }}" # Used by galaxy roles
    #globals
    galaxy_port: 80
    galaxy_user_uid: 1005 # Used by galaxy role and proftpd include
    galaxy_venv: "{{ galaxy_dir }}/.venv" # Used by galaxy and galaxy-tools roles 
    galaxy_server_dir: "{{ galaxy_dir }}" # Used by galaxy and galaxy-tools roles 
    galaxy_user_name: "{{ galaxy_user }}" # Used by galaxy-os and galaxy-tools roles 
    #persistent data
    galaxy_ftp: "{{ galaxy_data }}/database/ftp" # Used by artimed_extras and galaxy roles
    galaxy_config_dir: "{{ galaxy_data }}/config" # Used by artimed_extras and galaxy roles
    galaxy_mutable_data_dir: "{{ galaxy_data }}/database" # Used by artimed_extras and galaxy roles
    galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini" # Used by galaxy roles
    #persistent tool_sheds ???
    #tool_sheds_config_file: "{{ galaxy_server_dir }}/config/tool_sheds_conf.xml.sample"

  pre_tasks:
    #fix recreation of munge key
    - shell: rm -rf /tmp/slurm /etc/munge/munge.key
      when: install_galaxy

  roles:
    #installs system package requirements
    - role: galaxyprojectdotorg.galaxy-os
      configure_docker: no
      when: install_galaxy
    
    #move postgresql db to a persistent dir and symlinks to galaxy
    #- role: postgresql.movedb
    #  when: install_galaxy

    #check if config and database directories persisted on galaxy (it does nothing if galaxy_data == galaxy_dir)
    #- role: galaxy.movedata
    #  check_galaxy_data: yes
    #  when: install_galaxy

    #this role included in galaxyprojectdotorg.galaxy as a submodule to create galaxy user and its db 
    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user }}"
          password: "{{ galaxy_user }}"
      postgresql_objects_databases:
        - name: "{{ galaxy_user }}"
          owner: "{{ galaxy_user }}"
      sudo: yes
      sudo_user: postgres
      when: install_galaxy

    #installs galaxy
    - role: galaxyprojectdotorg.galaxy
      #persistent data
      galaxy_manage_mutable_setup: yes
      galaxy_mutable_config_dir: "{{ galaxy_config_dir }}"
      #other vars
      galaxy_manage_database: yes
      galaxy_fetch_eggs: no
      galaxy_changeset_id: master
      galaxy_vcs: git
      galaxy_venv_dir: "{{ galaxy_venv }}"
      galaxy_config:
        "app:main":
          admin_users: "{{ galaxy_admin }}"
          database_connection: "{{ galaxy_db }}"
          tool_dependency_dir: "{{ galaxy_dir }}/lib/tool_shed/dependencies"
          master_api_key: "{{ galaxy_api }}"
          ftp_upload_dir: "{{ galaxy_ftp }}" 
          ftp_upload_site: "ftp {{ galaxy_hostname }} port {{ ftp_port }}"
          #to be done only in production       
          #debug: False
          #use_interactive: False
          nginx_x_accel_redirect_base: "/_x_accel_redirect"
          nginx_x_archive_files_base: "/_x_accel_redirect"
          nginx_upload_store: "/tmp"
          nginx_upload_path: "/_upload"
        "uwsgi":
          stats: "localhost:9191"
          socket: "localhost:4001"
          master: True
          logto: "{{ galaxy_data }}/uwsgi.log"
          pythonpath: lib
          threads: 4
          processes: "{{ galaxy_web_processes }}"
      sudo: yes
      sudo_user: "{{ galaxy_user }}"
      when: install_galaxy

    #installs nginx and proftpd
    - role: galaxyprojectdotorg.galaxy-extras
      supervisor_slurm_config_dir: "{{ galaxy_data }}"
      galaxy_root: "{{ galaxy_dir }}"
      galaxy_log_dir: "{{ galaxy_data }}"
      galaxy_venv_dir:  "{{ galaxy_venv }}"
      galaxy_database_connection: "{{ galaxy_db }}"
      galaxy_extras_install_packages: true
      galaxy_extras_config_nginx: true
      galaxy_extras_config_supervisor: true
      galaxy_extras_config_proftpd: true
      galaxy_extras_config_uwsgi: true
      galaxy_extras_config_galaxy_job_metrics: true
      galaxy_extras_config_slurm: true
      galaxy_extras_config_galaxy_root: true
      galaxy_extras_config_ie_proxy: false
      supervisor_manage_postgres: false
      supervisor_manage_nginx: true
      supervisor_manage_proftp: true
      supervisor_manage_slurm: true
      supervisor_manage_reports: true
      supervisor_manage_docker: false
      supervisor_manage_nodeproxy: false
      supervisor_manage_ie_proxy: false      
      when: install_galaxy

    #fix proftpd config file, restarts supervisor
    - role: artimed_extras
      pbkdf2: true
      proftpd_conf_path:  "/etc/proftpd/proftpd.conf"
      proftpd_welcome: "Galaxy ARTiMED FTP server!"
      encoding: "base64"
      proftpd_db_connection: "{{ galaxy_user }}@localhost"
      proftpd_db_username: "{{ galaxy_user }}"
      proftpd_db_password: "{{ galaxy_user }}"
      auth_type: "PBKDF2"
      sql_query_user: "SELECT \"email, (CASE WHEN substring(password from 1 for 6) = 'PBKDF2' THEN substring(password from 38 for 69) ELSE password END) AS password2,512,512,'{{ galaxy_ftp }}/%U','/bin/bash' FROM galaxy_user WHERE email='%U'\""
      sql_query_alt: "SELECT \"(CASE WHEN SUBSTRING (password from 1 for 6) = 'PBKDF2' THEN SUBSTRING (password from 21 for 16) END) AS salt FROM galaxy_user WHERE email='%U'\""
      galaxy_user_gid: "{{ galaxy_user_uid }}"
      galaxy_user_uid: "{{ galaxy_user_uid }}"
      sql_pwd: "SHA256 10000 24"
      sql_alt: "sql:/GetUserSalt"
      when: install_galaxy
      
    #check if tool-data persisted on galaxy (it does nothing if galaxy_data == galaxy_dir)
    #- role: galaxy.movedata
    #  check_tool_data: yes
    #  when: install_galaxy

    - role: galaxyprojectdotorg.galaxy-tools #The default tools are listed in the file files/artimed_tool_list.yaml
      galaxy_tools_api_key: "{{ galaxy_api }}"
      galaxy_tools_admin_user: "{{ galaxy_admin }}"
      galaxy_tools_galaxy_instance_url: "localhost:{{ galaxy_port }}"
      galaxy_tools_tool_list_files: [ "{{ galaxy_tools }}" ]
      galaxy_venv_dir: "{{ galaxy_venv }}"
      when: install_tools
