- hosts: all
  become: yes

  environment: "{{ proxy_env }}"

  handlers:
    - include: roles/handlers/galaxy.yml
      static: yes

  pre_tasks:
    - fail: msg="Installed ansible version {{ ansible_version.full }}, but ansible version later than 2.1 required"
      when: "{{ ansible_version.full | version_compare('2.1.0.0', '<') }}"

    - set_fact:
        banner_img: "{% if 'jetstream' in group_names %}jetstream_text.png{% else %}gce_text.png{% endif %}"

  roles:

    - role: galaxyprojectdotorg.galaxy-os
      tags:
        - install_galaxy
        - install_packages

    - role: cloud_setup
      when: cloud_setup is defined

    - role: ensure_postgresql_up
      tags:
        - install_galaxy
        - manage_postgres

    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user_name }}"
          password: "{{ galaxy_user_name }}"
          encrypted: "yes"
      postgresql_objects_databases:
        - name: "{{ galaxy_user_name }}"
          owner: "{{ galaxy_user_name }}"
      become: yes
      become_user: postgres
      tags:
        - install_galaxy
        - manage_postgres

    - role: miniconda-role
      tags: conda
      become: yes
      become_user: "{{ galaxy_user_name }}"

    - role: galaxyprojectdotorg.galaxy
      become: yes
      become_user: "{{ galaxy_user_name }}"
      tags:
        - configure_galaxy
        - install_galaxy

    - role: set_supervisor_env_vars
      tags: env_vars

    - role: copy_additional_files
      tags:
        - install_extras

    # Installs supervisor, nginx and proftpd
    - role: galaxyprojectdotorg.galaxy-extras
      tags:
        - configure_server_stack
        - install_extras

    - role: ensure_postgresql_up
      tags:
        - manage_postgres
        - install_tools

    - role: galaxy.movedata
      tags:
        - persists_galaxy

    - role: galaxyprojectdotorg.trackster
      tags: configure_galaxy

    - role: galaxyprojectdotorg.galaxy-tools
      become: yes
      become_user: "{{ galaxy_user_name }}"
      tags: install_tools

  post_tasks:
    - name: Clean apt cache to recover some disk space
      shell: apt-get clean

    # htop is a placeholder here; see bug report
    # https://github.com/ansible/ansible-modules-core/issues/4029
    - name: Apt autoremove
      apt: autoremove=yes name=htop
