- hosts: all
  sudo: yes

  roles:
    #installs system package requirements
    - role: galaxyprojectdotorg.galaxy-os
      configure_docker: no
    
    #move postgresql db to a persistent dir and symlinks to galaxy
    #- role: postgresql.movedb
    #  when: install_galaxy

    - role: ensure_postgresql_up

    #this role included in galaxyprojectdotorg.galaxy as a submodule to create galaxy user and its db 
    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user_name }}"
          password: "{{ galaxy_user_name }}"
      postgresql_objects_databases:
        - name: "{{ galaxy_user_name }}"
          owner: "{{ galaxy_user_name }}"
      sudo: yes
      sudo_user: postgres

    #installs galaxy
    - role: galaxyprojectdotorg.galaxy
      sudo: yes
      sudo_user: "{{ galaxy_user_name }}"
      tags: configure_galaxy

    #installs supervisor, nginx and proftpd
    - role: galaxyprojectdotorg.galaxy-extras
      supervisor_postgres_database_path: "{{ supervisor_postgres_database_path_discovered }}"
      postgresql_version: "{{ supervisor_postgres_database_version_discovered }}"
      tags: configure_server_stack

    #fix proftpd config file, restarts supervisor, put the test tool shed in the list and create a welcome page
    - role: ensure_postgresql_up

    - role: artimed_extras
      run_extras: true
      pbkdf2: true
      create_galaxy_admin: true
      restart_galaxy: true
      when: install_galaxy
      
    - role: galaxy.movedata
      tags: 
        - persists_galaxy

    - role: galaxyprojectdotorg.galaxy-tools
      sudo: yes
      sudo_user: "{{ galaxy_user_name }}"
      tags: install_tools
      when: install_tools

    - role: galaxyprojectdotorg.galaxy-tools
      sudo: yes
      sudo_user: "{{ galaxy_user_name }}"
      tags: install_tools
      galaxy_tools_tool_list: "{{ galaxy_data_manager_tool_list }}"
      when: run_data_manager

    #Restart Galaxy
    - role: artimed_extras
      restart_galaxy: true
      when: install_tools or run_data_manager
