- hosts: all
  become: yes

  handlers:
    - include: roles/handlers/galaxy.yml
      static: yes

  pre_tasks:
    - fail: msg="Installed ansible version {{ ansible_version.full }}, but ansible version later than 2.1 required"
      when: "{{ ansible_version.full | version_compare('2.1.0.0', '<') }}"

  roles:

    - role: GKS-slave_node
      tags:
        - configure_slurm_slave_node

  post_tasks:
    - name: Clean apt cache to recover some disk space
      shell: apt-get clean

    # htop is a placeholder here; see bug report
    # https://github.com/ansible/ansible-modules-core/issues/4029
    - name: Apt autoremove
      apt: autoremove=yes name=htop
