- name: Stop supervisor postgreSQL
  supervisorctl: name="postgresql" state=stopped
  when: not service_postgresql
  register: supervisor_postgresql_success
  ignore_errors: yes
  
- name: Stop postgresql
  service: name=postgresql state=stopped
  when: service_postgresql or supervisor_postgresql_success.failed is defined

- name: Create users group
  group: name=users state=present

- name: Put postgres into users group
  shell: adduser postgres users
#  user: name=postgres groups="postgres,users"

- name: Check postgresql dir for galaxy
  stat: path={{ galaxy_database }}
  register: dir_sym

- name: Create postgresql dir for galaxy
  file: path={{ galaxy_database }} owner=postgres group=postgres mode=0700 state=directory
  when: dir_sym.stat.islnk is not defined

- name: Give postgres access to galaxy_database directory chain
  file: path=/{{ galaxy_database_items[1] }} mode=0755 group=users #recurse=yes
#  with_items: "{{ galaxy_database_items }}"
  when: galaxy_database_items[1] is defined

- name: Postgresql version
  shell: ls -C1 /etc/postgresql/
  register: postgresql_version

#upgrade: automaticlly dicovers where is the postgresql master db (pg_lsclusters)
- name: Copy postgresql db
  shell: cp -vr /var/lib/postgresql/{{ postgresql_version.stdout }}/main {{ galaxy_database }}/
  when: dir_sym.stat.islnk is not defined
  sudo: yes
  sudo_user: postgres

- name: Check postgresql backup dir
  stat: path=/var/lib/postgresql/{{ postgresql_version.stdout }}/main.backup/PG_VERSION
  register: dir_sym

- name: Backup postgresql db
  shell: mv -v /var/lib/postgresql/{{ postgresql_version.stdout }}/main /var/lib/postgresql/{{ postgresql_version.stdout }}/main.backup
  when: dir_sym.stat.islnk is not defined
  sudo: yes
  sudo_user: postgres

- name: Check postgresql symlink for galaxy
  stat: path=/var/lib/postgresql/{{ postgresql_version.stdout }}/main
  register: dir_sym

- name: Create a symlink for postgresql
  shell: ln -s {{ galaxy_database }}/main /var/lib/postgresql/{{ postgresql_version.stdout }}/
  when: dir_sym.stat.islnk is not defined or not dir_sym.stat.islnk
  sudo: yes
  sudo_user: postgres

- set_fact:
    supervisor_postgres_database_path: "/var/lib/postgresql/{{ postgresql_version.stdout }}/main\" -c \"config_file=/etc/postgresql/{{ postgresql_version.stdout }}/main/postgresql.conf"

- name: Start supervisor postgreSQL
  supervisorctl: name="postgresql" state=started
  when: not service_postgresql
  register: supervisor_postgresql_success
  ignore_errors: yes

- name: Start postgresql
  service: name=postgresql state=started
  when: service_postgresql or supervisor_postgresql_success.failed is defined
  