- name: Update APT cache
  apt: update_cache=yes

- name: Install Galaxy system packages
  apt: pkg={{ item }} state='latest' install_recommends=no
  with_items:
    - build-essential
    - samtools
    - htop
    
