- name: Install SLURM system packages
  apt: pkg={{ item }} state='present'
  with_items:
    - munge
    - slurm-llnl
    - slurm-drmaa-dev
    - python-psutil

- name: Install SLURM system packages
  apt: pkg={{ item }} state='present'
  with_items:
    - slurm-llnl-torque
  when: ansible_distribution_version <= "15.04"

- name: Install SLURM system packages
  apt: pkg={{ item }} state='present'
  with_items:
    - slurm-wlm-torque
  when: ansible_distribution_version >= "15.04"

- name: Create Munge Key
  command: /usr/sbin/create-munge-key creates=/etc/munge/munge.key

- name: Setup Munge permissions and folder
  file: path={{ item }} state=directory owner=root group=root recurse=yes
  with_items:
    - /var/run/munge
    - /var/lib/munge
    - /var/log/munge
    - /var/run/munge
    - /etc/munge

- name: Setup tmp area for slurm.
  file: path=/tmp/slurm state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_gid }}

