
- name: Install supervisor
  apt: pkg='supervisor' state='present'

- name: Create supervisor configuration directory.
  file: path={{ supervisor_conf_path }} state=directory mode=0755

- name: Create supervisor configuration file
  template: src=supervisor.conf.j2 dest={{ supervisor_conf_path }}/supervisord.conf

- name: Stop supervisor        
  service: name=supervisor state=stopped        
  tags: stop_supervisor        
      
- name: Stop and remove munge.        
  service: name={{ item }} state=stopped enabled=no        
  with_items:        
    - munge        

- name: Stop and remove slurm.
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - slurm-llnl
  when: ansible_distribution_version <= "15.04"

- name: Stop and remove slurm.
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - slurmd
    - slurmctld
  when: ansible_distribution_version > "15.04"

- name: Start supervisor
  service: name=supervisor state=started
