---
# Add system users

- name: Add shadow groups
  group: name=shadow system=yes

- name: Add galaxy user
  user: name={{ galaxy_user_name }} uid={{ galaxy_user_uid }} shell=/bin/bash groups={{ galaxy_user_gid }},shadow

- name: Add nobody user to shadow group
  user: name=nobody groups=shadow
