- hosts: all
  remote_user: "{{ lookup('env','INSTALL_USER') }}"
  sudo: yes

  vars:
    #Globals
    galaxy_hostname: "{{ lookup('env','INSTALL_HOSTNAME') }}"
    galaxy_user: "{{ lookup('env','GALAXY_USER') }}"
    galaxy_port: "{{ lookup('env','GALAXY_PORT') }}"
    galaxy_host: "0.0.0.0"
    galaxy_admin: "artimed@gmail.com"
    galaxy_dir: "/home/{{ galaxy_user }}/{{ galaxy_user }}"
    galaxy_venv: "{{ galaxy_dir }}/venv/"
    galaxy_ftp: "{{ galaxy_dir }}/database/files/"
    ftp_port: "{{ lookup('env','FTP_PORT') }}"
    galaxy_api: 379ab2a47d714a74b5cee4081703368e
    galaxy_db: "postgresql:///{{ galaxy_user }}?host=/var/run/postgresql"

  roles:
    #installs system package requirements
    - role: galaxyprojectdotorg.galaxy-os
      configure_docker: no
      galaxy_user_name: "{{ galaxy_user }}"
      galaxy_user_uid: 1055

    #this role included in galaxyprojectdotorg.galaxy as a submodule to create galaxy user and its db
    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user }}"
          password: "{{ galaxy_user }}"
      postgresql_objects_databases:
        - name: "{{ galaxy_user }}"
          owner: "{{ galaxy_user }}"
      sudo: yes
      sudo_user: postgres

    #installs galaxy
    - role: galaxyprojectdotorg.galaxy
      #galaxy_manage_clone: no
      galaxy_manage_database: no
      galaxy_fetch_eggs: no
      galaxy_changeset_id: master
      galaxy_vcs: git
      galaxy_venv_dir: "{{ galaxy_venv }}"
      galaxy_server_dir: "{{ galaxy_dir }}/"
      galaxy_config_dir: "{{ galaxy_dir }}/config/"
      galaxy_config:
        "server:main":
          host: "{{ galaxy_host }}"
          port: "{{ galaxy_port }}"
        "app:main":
          admin_users: "{{ galaxy_admin }}"
          database_connection: "{{ galaxy_db }}"
          tool_dependency_dir: "{{ galaxy_dir }}/lib/tool_shed/dependencies/"
          master_api_key: "{{ galaxy_api }}"
          ftp_upload_dir: "{{ galaxy_ftp }}" 
          ftp_upload_site: "ftp {{ galaxy_hostname }} port {{ ftp_port }}"
          #to be done only in production       
          #debug: False
          #use_interactive: False
      sudo: yes
      sudo_user: "{{ galaxy_user }}"

    #installs nginx and proftpd
    - role: galaxyprojectdotorg.galaxy-extras
      galaxy_root: "{{ galaxy_dir }}/"
      galaxy_venv_dir:  "{{ galaxy_venv }}"
      galaxy_database_connection: "{{ galaxy_db }}"
      galaxy_paste_handlers: true
      galaxy_extras_install_packages: true
      galaxy_extras_config_nginx: true
      galaxy_extras_config_supervisor: true
      galaxy_extras_config_proftpd: true
      galaxy_extras_config_uwsgi: true
      galaxy_extras_config_galaxy_job_metrics: true
      galaxy_extras_config_slurm: true
      galaxy_extras_config_galaxy_root: true
      galaxy_extras_config_ie_proxy: true
      galaxy_extras_config_scripts: false
      galaxy_extras_config_startup: false
      supervisor_manage_proftp: true
      supervisor_manage_ie_proxy: true
      supervisor_manage_docker: false
      supervisor_manage_reports: true
      supervisor_manage_nodeproxy: false