- name: Check data dir for galaxy
  stat: path={{ galaxy_data }}
  register: directory

- name: Create data dir for galaxy
  file: path={{ galaxy_data }} owner={{ galaxy_user }} group={{ galaxy_user }} mode=0700 state=directory
  when: directory.stat.islnk is not defined and persist
  