- name: Check tool-data dir for galaxy
  stat: path={{ galaxy_data }}/tool-data
  register: directory
  when: persist

- name: Check tool-data dir symlink for galaxy
  stat: path={{ galaxy_dir }}/tool-data
  register: symlink
  when: persist

- name: Stop galaxy
  supervisorctl: name="galaxy:" state=stopped
  ignore_errors: yes
  when: persist and not symlink.stat.islnk 

- name: Create tool-data dir for galaxy
  file: path={{ galaxy_data }}/tool-data owner={{ galaxy_user }} group={{ galaxy_user }} mode=0700 state=directory
  when: persist and directory.stat.islnk is not defined

- name: Move galaxy tool-data to backup
  shell: mv -v {{ galaxy_dir }}/tool-data {{ galaxy_dir }}/tool-data.backup 
  when: persist and not symlink.stat.islnk
  sudo: yes
  sudo_user: "{{ galaxy_user }}"

- name: Create a symlink for galaxy tool-data
  shell: ln -s {{ galaxy_data }}/tool-data {{ galaxy_dir }}/
  when: persist and not symlink.stat.islnk
  sudo: yes
  sudo_user: "{{ galaxy_user }}"
  
- name: Copy galaxy tool-data to persistent
  shell: cp -vr {{ galaxy_dir }}/tool-data.backup/ {{ galaxy_dir }}/tool-data/
  when: persist and directory.stat.islnk is not defined
  sudo: yes
  sudo_user: "{{ galaxy_user }}"

- name: Start galaxy
  supervisorctl: name="galaxy:" state=started
  ignore_errors: yes
  when: persist and not symlink.stat.islnk 
