- name: start galaxy
  supervisorctl: name='galaxy:' state=started

# Restarting galaxy is only necessary when not running docker
- name: restart galaxy
  supervisorctl: name='galaxy:' state=restarted
  when: ansible_virtualization_type != "docker"
