FROM artbio/galaxy-kickstart-metavisitor-base

MAINTAINER Marius van den Beek <m.vandenbeek@gmail.com>

# Expose port 80 (webserver), 21 (FTP server), 8800 (Proxy), 9002 (supvisord web app)
EXPOSE :80
EXPOSE :21
EXPOSE :8800
EXPOSE :9002

# Mark folders as imported from the host.
VOLUME ["/export", "/var/lib/docker"]

CMD ansible-playbook galaxy.yml -c local --tags persists_galaxy --skip-tags=skip_supervisor_start_in_docker -i docker_metavisitor_inventory && \
           /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf --nodaemon
