- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the data manager script
  copy: src=roles/galaxyprojectdotorg.galaxy-tools/files/install_tool_shed_tools.py dest={{ galaxy_tools_base_dir }}/

- name: Copy data manager task file
  copy: src={{ data_manager_task_file }} dest={{ galaxy_tools_base_dir }}/

- name: Run data managers
  command: "{{ galaxy_tools_base_dir }}/venv/bin/python install_tool_shed_tools.py -d {{ data_manager_task_file }} -a {{ default_admin_api_key }} -g {{ galaxy_hostname }}"
  args:
    chdir: "{{ galaxy_tools_base_dir }}"
