- include: galaxy_admin.yml
  when: create_galaxy_admin

- include: extras.yml
  when: run_extras
  
- include: data_managers.yml
  when: run_data_managers

- include: supervisor_galaxy.yml
  when: restart_galaxy or start_galaxy or stop_galaxy
