- hosts: ARTiMED_host_servers
  remote_user: root
  sudo: yes

  vars:
    local_user: "{{ LOCAL_USER }}"
    vm_dir: "{{ VM_DIR }}"
    vagrant_package: vagrant
    virtualbox_package: virtualbox
    vagrant_file: Vagrantfile
    
  tasks:
  - name: install vagrant on Debian
    apt: pkg={{ vagrant_package }} state=latest update_cache=yes
    when: ansible_os_family == "Debian"

  - name: install vagrant on RedHat
    yum: name={{ vagrant_package }} state=latest
    when: ansible_os_family == "RedHat"
    
  - name: install virtualbox on Debian
    apt: pkg={{ virtualbox_package }} state=latest 
    when: ansible_os_family == "Debian"
    
  - name: install virtualbox on RedHat
    yum: name={{ virtualbox_package }} state=latest
    when: ansible_os_family == "RedHat"

  - name: Assures vm dir exists
    file: path={{ vm_dir }} state=directory
    become_user: "{{ local_user }}"
    become_method: sudo    
    
  - shell: VAGRANT_LOG=info vagrant upvagrant up
    args:
      chdir: "{{ vm_dir }}"
    become_user: "{{ local_user }}"
    become_method: sudo
