- hosts: ARTiMED_host_servers
  remote_user: "{{ lookup('env','USER') }}"
  sudo: yes

  vars:
    vm_dir: "{{ VM_DIR }}"
    vagrant_package: vagrant
    virtualbox_package: virtualbox
    vagrant_box: https://dl.dropboxusercontent.com/u/3523744/boxes/debian-8.1-amd64-lxc-puppet/debian-8.1-lxc-puppet.box
    vagrant_file: Vagrantfile
    
  tasks:
  - name: install vagrant on Debian
    apt: pkg={{ vagrant_package }} state=latest update_cache=yes
    when: ansible_os_family == "Debian"
    become: yes
    become_method: sudo    

  - name: install vagrant on RedHat
    yum: name={{ vagrant_package }} state=latest
    when: ansible_os_family == "RedHat"
    become: yes
    become_method: sudo    
    
  - name: install virtualbox on Debian
    apt: pkg={{ virtualbox_package }} state=latest 
    when: ansible_os_family == "Debian"
    become: yes
    become_method: sudo    
    
  - name: install virtualbox on RedHat
    yum: name={{ virtualbox_package }} state=latest
    when: ansible_os_family == "RedHat"
    become: yes
    become_method: sudo    

  - name: Assures vm dir exists
    file: path={{ vm_dir }} state=directory
    
  - replace: dest={{ vm_dir }}/{{ vagrant_file }} regexp='VAGRANT_BOX' replace='{{ vagrant_box }}' backup=yes

  - shell: vagrant up
    args:
      chdir: "{{ vm_dir }}"
