- hosts: ARTiMED_host_servers
  remote_user: fabiorjvieira
  sudo: yes

  vars:
    local_home: "{{ lookup('env','HOME') }}"
    vm_dir: galaxy_install
    vagrant_package: vagrant
    virtualbox_package: virtualbox
    vagrant_box: https://dl.dropboxusercontent.com/u/3523744/boxes/debian-8.1-amd64-lxc-puppet/debian-8.1-lxc-puppet.box
    vagrant_file: Vagrantfile
    
  tasks:
  - name: install vagrant on Debian
    apt: pkg={{ vagrant_package }} state=latest update_cache=yes
    when: ansible_os_family == "Debian"
    register: vagrant_result
