    #Correcting proftpdir settings for PBKDF2
    - lineinfile: dest=/etc/proftpd/proftpd.conf regexp='^Port' line="Port {{ ftp_port }}" state=present 
      sudo: yes
      sudo_user: root
    
    - lineinfile: dest=/etc/proftpd/proftpd.conf regexp='^SQLPasswordEncoding' line='SQLPasswordEncoding base64' state=present 
      sudo: yes
      sudo_user: root
    
    - lineinfile: dest=/etc/proftpd/proftpd.conf regexp='^SQLAuthTypes' line='SQLAuthTypes PBKDF2' state=present 
      sudo: yes
      sudo_user: root

    - lineinfile: dest=/etc/proftpd/proftpd.conf regexp='^SQLNamedQuery' line="SQLNamedQuery LookupGalaxyUser SELECT \"email, (CASE WHEN substring(password from 1 for 6) = 'PBKDF2' THEN substring(password from 38 for 69) ELSE password END) AS password2,512,512,'/home/galaxy/galaxy/database/files/%U','/bin/bash' FROM galaxy_user WHERE email='%U'\"" state=present 
      sudo: yes
      sudo_user: root
    
    - lineinfile: dest=/etc/proftpd/proftpd.conf line="SQLNamedQuery GetUserSalt SELECT \"(CASE WHEN SUBSTRING (password from 1 for 6) = 'PBKDF2' THEN SUBSTRING (password from 21 for 16) END) AS salt FROM galaxy_user WHERE email='%U'\"" insertafter=EOF state=present
      sudo: yes
      sudo_user: root
    
    - lineinfile: dest=/etc/proftpd/proftpd.conf line="SQLDefaultGID {{ galaxy_user_uid }}" insertafter=EOF state=present
      sudo: yes
      sudo_user: root
      
    - lineinfile: dest=/etc/proftpd/proftpd.conf line="SQLDefaultUID {{ galaxy_user_uid }}" insertafter=EOF state=present
      sudo: yes
      sudo_user: root
      
    - lineinfile: dest=/etc/proftpd/proftpd.conf line="SQLPasswordPBKDF2 SHA256 10000 24 " insertafter=EOF state=present
      sudo: yes
      sudo_user: root
      
    - lineinfile: dest=/etc/proftpd/proftpd.conf line="SQLPasswordUserSalt sql:/GetUserSalt" insertafter=EOF state=present
      sudo: yes
      sudo_user: root