- hosts: ARTiMED_host_servers
  remote_user: root
  sudo: yes

  vars:
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ LOCAL_USER }}"
    vm_dir: "{{ VM_DIR }}"
    vagrant_package: vagrant
    virtualbox_package: virtualbox
    
  tasks:
  - name: install dependencies packages on debian
    action: apt pkg={{ item }} state=latest update_cache=yes
    with_items:
       - "{{ vagrant_package }}"
       - "{{ virtualbox_package }}"
    when: ansible_os_family == "Debian"

  - name: install dependencies packages on debian
    action: yum pkg={{ item }} state=latest update_cache=yes
    with_items:
       - "{{ vagrant_package }}"
       - "{{ virtualbox_package }}"
    when: ansible_os_family == "RedHat"

  - name: Assures vm dir exists
    file: path={{ vm_dir }} state=directory
    become_user: "{{ local_user }}"
    become_method: sudo    

  - replace: dest={{ vm_dir }}/Vagrantfile regexp='\$HOME' replace='{{ local_home }}' backup=yes
    become_user: "{{ local_user }}"
    become_method: sudo    

  - git: repo=https://github.com/galaxyproject/ansible-postgresql.git dest={{ vm_dir }}/roles/postgresql clone=yes update=yes
    become_user: "{{ local_user }}"
    become_method: sudo    

  - lineinfile: dest={{ vm_dir }}/roles/postgresql/tasks/debian.yml line="- shell: pg_createcluster \{\{ postgresql_version \}\} main --start \n  ignore_errors: yes" insertafter="EOF" state=present
    become_user: "{{ local_user }}"
    become_method: sudo
   
  - shell: VAGRANT_LOG=info vagrant up
    args:
      chdir: "{{ vm_dir }}"
    become_user: "{{ local_user }}"
    become_method: sudo
