- hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    #Globals
    galaxy_user: galaxy
    galaxy_port: 8080
    galaxy_host: "0.0.0.0"
    galaxy_admin: "artimed@gmail.com"
    galaxy_dir: "/home/{{ galaxy_user }}/{{ galaxy_user }}"
    galaxy_venv: /home/{{ galaxy_user }}/venv/
    galaxy_api: 379ab2a47d714a74b5cee4081703368e

  roles:
    #installs system package requirements
    - role: galaxyprojectdotorg.galaxy-os
      configure_docker: no
      galaxy_user_name: "{{ galaxy_user }}"
      galaxy_user_uid: 1005

    #this role included in galaxyprojectdotorg.galaxy as a submodule to create galaxy user and its db
    - role: natefoo.postgresql_objects
      postgresql_objects_users:
        - name: "{{ galaxy_user }}"
          password: "{{ galaxy_user }}"
      postgresql_objects_databases:
        - name: "{{ galaxy_user }}"
          owner: "{{ galaxy_user }}"
      sudo: yes
      sudo_user: postgres

    #installs galaxy
    - role: galaxyprojectdotorg.galaxy
      #galaxy_manage_clone: no
      galaxy_manage_database: no
      galaxy_fetch_eggs: yes
      galaxy_changeset_id: master
      galaxy_vcs: git
      galaxy_venv_dir: "{{ galaxy_venv }}"
      galaxy_server_dir: "{{ galaxy_dir }}/"
      galaxy_config_dir: "{{ galaxy_dir }}/config/"
      galaxy_config:
        "server:main":
          host: "{{ galaxy_host }}"
          port: "{{ galaxy_port }}"
        "app:main":
          admin_users: "{{ galaxy_admin }}"
          database_connection: "postgresql:///{{ galaxy_user }}?host=/var/run/postgresql"
          tool_dependency_dir: "{{ galaxy_dir }}/lib/tool_shed/dependencies/"
          master_api_key: "{{ galaxy_api }}"
          #to be done only in production       
          #debug: False
          #use_interactive: False
      sudo: yes
      sudo_user: "{{ galaxy_user }}"

    #installs supervisor, nginx, proftpd, uwsgi
    - role: galaxyprojectdotorg.galaxy-extras
      galaxy_extras_install_packages: true
      galaxy_extras_config_nginx: true
      galaxy_extras_config_supervisor: true
      galaxy_extras_config_proftpd: true
      galaxy_extras_config_uwsgi: true
      galaxy_extras_config_galaxy_job_metrics: true
      galaxy_extras_config_slurm: false
      galaxy_extras_config_galaxy_root: false
      galaxy_extras_config_ie_proxy: false
      galaxy_extras_config_scripts: false
      galaxy_extras_config_startup: false
      supervisor_manage_proftp: yes
      supervisor_manage_ie_proxy: yes
      supervisor_manage_docker: false
      supervisor_manage_nodeproxy: false
      galaxy_root: "{{ galaxy_dir }}/"
      galaxy_venv_dir:  "{{ galaxy_venv }}"
      galaxy_database_connection: "{{ database_connection }}"

#  task:
#Create a system service for galaxy
#  - shell: cp /home/{{ galaxy_user }}/{{ galaxy_user }}/contrib/galaxy.debian-init /etc/init.d/{{ galaxy_user }}
#    become_user: root
#    become_method: sudo    

#  - replace: dest=/etc/init.d/{{ galaxy_user }} regexp="galaxy_dist" replace="{{ galaxy_user }}" backup=yes

#  - command: update-rc.d galaxy defaults
#    become_user: root
#    become_method: sudo    

#  - service: name={{ galaxy_user }} state=started
#    become_user: root
#    become_method: sudo  
