- hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    galaxy_user: galaxy
    galaxy_relative_dir: galaxy_dist
    galaxy_ip: 0.0.0.0
    galaxy_port: 8080
    git_package: git 
    build_package: build-essential
    python_postgres: python-psycopg2
    postgresql_conf:
      listen_addresses: "''"    # disable network listening (listen on unix socket only)
    postgresql_pg_hba_conf:
      - host all all 10.0.0.0/8 md5

  roles:
    - postgresql
        
  tasks:
  - locale_gen: name=en_US.UTF-8 state=present

  - name: install dependencies packages
    action: apt pkg={{ item }} state=latest update_cache=yes
    with_items:
       - "{{ build_package }}"
       - "{{ git_package }}"
       - "{{ python_postgres }}"
    become_user: root
    become_method: sudo

#Linux user
  - user: name={{ galaxy_user }} shell=/bin/bash groups=admin password={{ galaxy_user }} home=/home/{{ galaxy_user }}/ createhome=yes append=yes
    become_user: root
    become_method: sudo    

#PostgreSQL
  - include: ./postgresql/handlers/main.yml 

  - postgresql_user: name={{ galaxy_user }}
    become_user: postgres
    become_method: sudo    

  - postgresql_db: name={{ galaxy_user }} owner={{ galaxy_user }}
    become_user: postgres
    become_method: sudo    

#Galaxy
  - git: repo=https://github.com/galaxyproject/galaxy.git dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/ clone=yes update=yes
    become_user: "{{ galaxy_user }}"
    become_method: sudo    

  - shell: cp /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/galaxy.ini.sample /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/galaxy.ini
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - shell: cp /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/tool_sheds_conf.xml.sample /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/tool_sheds_conf.xml
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - replace: dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/galaxy.ini regexp='#host = 127.0.0.1' replace='host = {{ galaxy_ip }}' backup=no
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - replace: dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/galaxy.ini regexp='#tool_dependency_dir = None' replace='tool_dependency_dir = ../dependencies/' backup=no
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - replace: dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/galaxy.ini regexp='#admin_users = None' replace='admin_users = artimed@gmail.com' backup=no
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - lineinfile: dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/galaxy.ini line='database_connection = postgresql:///{{ galaxy_user }}?host=/var/run/postgresql' insertafter='^#database_connection = ' state=present
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - lineinfile: dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/tool_sheds_conf.xml line='    <tool_shed name="ARTbio Tool Shed" url="https://lbcd41.snv.jussieu.fr/toolshed/"/>' insertafter='<tool_sheds>' state=present
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - shell: cp /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/contrib/galaxy.debian-init /etc/init.d/{{ galaxy_user }}
    become_user: root
    become_method: sudo
 
#  - service: name={{ galaxy_user }} state=started
#    become_user: root
#    become_method: sudo    
