- hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    galaxy_user: galaxy
    galaxy_relative_dir: galaxy_dist
    galaxy_ip: 0.0.0.0
    admin_user: artimed@gmail.com

    git_package: git 
    build_package: build-essential
    python_postgres: python-psycopg2

    galaxy_vcs: git
    galaxy_server_dir: "/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/"
    postgresql_objects_users:
      - name: galaxy
        password: null
    postgresql_objects_databases:
      - name: galaxy
        owner: galaxy
    galaxy_config:
      "server:main":
        host: "{{ galaxy_ip }}"
      "app:main":
        admin_users: "{{ admin_user }}"
        database_connection: "postgresql:///{{ galaxy_user }}?host=/var/run/postgresql"
        tool_dependency_dir: "../dependencies/"

  pre_tasks:
  - name: install pre-dependencies packages
    action: apt pkg={{ item }} state=latest update_cache=yes
    with_items:
       - "{{ build_package }}"
       - "{{ git_package }}"
    become_user: root
    become_method: sudo    

  #Linux galaxy user
  - user: name={{ galaxy_user }} shell=/bin/bash groups=admin password={{ galaxy_user }} home=/home/{{ galaxy_user }}/ createhome=yes append=yes system=yes 
    become_user: root
    become_method: sudo    

  roles:
    - galaxyprojectdotorg.postgresql
    - role: galaxyprojectdotorg.galaxy
      sudo: yes
      sudo_user: "{{ galaxy_user }}"
        
  tasks:
  - name: install dependencies packages
    action: apt pkg={{ item }} state=latest update_cache=no
    with_items:
       - "{{ python_postgres }}"
    become_user: root
    become_method: sudo    

  #PostgreSQL
  - postgresql_user: name={{ galaxy_user }}
    become_user: postgres
    become_method: sudo    

  - postgresql_db: name={{ galaxy_user }} owner={{ galaxy_user }}
    become_user: postgres
    become_method: sudo    

  #Galaxy tool sheds
  - shell: cp /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/tool_sheds_conf.xml.sample /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/tool_sheds_conf.xml
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - lineinfile: dest=/home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/config/tool_sheds_conf.xml line='    <tool_shed name="ARTbio Tool Shed" url="https://lbcd41.snv.jussieu.fr/toolshed/"/>' insertafter='<tool_sheds>' state=present
    become_user: "{{ galaxy_user }}"
    become_method: sudo

  - shell: cp /home/{{ galaxy_user }}/{{ galaxy_relative_dir }}/contrib/galaxy.debian-init /etc/init.d/{{ galaxy_user }}
    become_user: root
    become_method: sudo    

#  - service: name={{ galaxy_user }} state=started
#    become_user: root
#    become_method: sudo    
