VAGRANTFILE_API_VERSION = "2"
   Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
      config.vm.box = "ubuntu/trusty64"
      config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 80, host: 8081
      config.vm.network "forwarded_port", guest: 2121, host: 2121

      config.vm.provider "virtualbox" do |v|
         v.memory = 4096
      end
      
      if ENV['PLAYBOOK']
         config.vm.provision "ansible" do |ansible|
            ansible.extra_vars = {
               ntp_server: "pool.ntp.org",
            }
            ansible.verbose = 'vvvv'
            ansible.playbook = "#{ENV['PLAYBOOK']}"
         end
      end
   end
