runtime! debian.vim

" Handle common command typos
:command WQ wq
:command Wq wq
:command W w
:command Q q

syntax on
set background=dark
set shiftwidth=4
set tabstop=4
set expandtab          " Use spaces instead of tabs
"color cmustang

if has("autocmd")
  filetype plugin indent on
endif

set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set ignorecase          " Do case insensitive matching
set smartcase           " Do smart case matching
set incsearch           " Incremental search
set hidden              " Hide buffers when they are abandoned
set number              " line numbers
set cursorline          " Highlight current line

filetype on                   " Enable filetype detection
filetype indent on            " Enable filetype-specific indenting
set autoindent smartindent    " auto/smart indent

highlight LineNr ctermfg=grey ctermbg=234 guibg=#202020 " Set color of the line numbers

" Have 3 lines of offset (or buffer) when scrolling
set scrolloff=3

" Automatically set/unset Vim's paste mode when you paste
" http://bit.ly/1GpolV2
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
