name: Ansible Testing
on:
  push:
    branches:
      - master
  
env:
  GALAXY_USER: admin@galaxy.org
  GALAXY_USER_PASSWD: artbio2020
  BIOBLEND_GALAXY_API_KEY: "artbio2020"
  BIOBLEND_GALAXY_URL: "http://127.0.0.1:80"


jobs:
  Ubuntu_18:
    name: GalaxyKickStart in ubuntu18.04
    runs-on: ubuntu-18.04
#    env:
#        BIOBLEND_TEST_JOB_TIMEOUT: "120"
    
    steps:
    - name: Remove PostgreSQL on VM
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo apt-get --purge remove postgresql
        dpkg -l | grep postgres
        sudo apt-get --purge remove pgdg-keyring postgresql*
        sudo rm -rf /var/lib/postgresql/  # directory data postgresql
        sudo rm -rf /var/log/postgresql/  # directory log postgresql
        sudo rm -rf /etc/postgresql/  # directory base postgresql
        sudo deluser postgres
        sudo apt-get update -y

    - name: Set up Python 3.7 in ubuntu 18.04
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    
    - name: Set up pip and ansible in ubuntu 18.04
      run: |
        python3 -m pip install -U pip setuptools 
        python3 -m pip install ansible==2.7.4
        python3 -m pip install --ignore-installed https://github.com/galaxyproject/bioblend/archive/refs/tags/v0.15.0.zip pytest
    
    - name: Display pip python and ansible settings
      run: |
        which python
        python --version
        which python3
        python3 --version
        ansible --version
        pip show pytest
        pip show bioblend

    - uses: actions/checkout@v2

    - name: install ansible roles
      run: |
        ansible-galaxy install -r requirements_roles.yml -p roles

    - name: ansible installs galaxy
      run: |
        sudo apt-get update -y
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
        sudo apt-get --purge remove nginx*
        ansible-playbook -i inventory_files/galaxy-kickstart --extra-vars RUNNER_ALLOW_RUNASROOT="1" galaxy.yml

    - name: Sleep for 10 seconds
      run: |
        echo "waiting 10 sec" && sleep 10
            
    - name: restart galaxy services with supervisorctl
      run: |
        sudo supervisorctl restart galaxy:

    - name: Sleep for 10 seconds
      run: |
        echo "waiting 10 sec" && sleep 10

    - name: check Galaxy API is alive
      uses: mydea/action-wait-for-api@v1
      with:
        url: "http://localhost/api/version"
        timeout: 120

    - name: ansible installs galaxy tools
      run: |
        ansible-playbook -i inventory_files/galaxy-kickstart --extra-vars RUNNER_ALLOW_RUNASROOT="1" galaxy_tool_install.yml

    - name: run basic tests
      run: |
        sudo supervisorctl status
        curl http://localhost:80/api/version| grep version_major
        echo "\ntest ftp transfer to proftpd server\n"
        date > date.txt && curl --fail -T date.txt ftp://127.0.0.1:21 --user $GALAXY_USER:$GALAXY_USER_PASSWD

    - name: Bioblend tests
      run: |
        cd /opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/bioblend/_tests/
        bioblend-galaxy-tests --color=yes -v TestGalaxyHistories.py TestGalaxyTools.py --no-summary || true



  Ubuntu_16:
    name: GalaxyKickStart in ubuntu16.04
#    needs: Ubuntu_18
    runs-on: ubuntu-16.04
#    env:
#      BIOBLEND_TEST_JOB_TIMEOUT: "120"
    
    steps:
    - name: Remove PostgreSQL on VM
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo apt-get --purge remove postgresql
        dpkg -l | grep postgres
        sudo apt-get --purge remove pgdg-keyring postgresql*
        sudo rm -rf /var/lib/postgresql/  # directory data postgresql
        sudo rm -rf /var/log/postgresql/  # directory log postgresql
        sudo rm -rf /etc/postgresql/  # directory base postgresql
        sudo deluser postgres
        sudo apt-get update -y
    
    - name: Set up Python 3.7 in ubuntu 16.04
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Set up pip and ansible in ubuntu 16.04
      run: |
        python3 -m pip install -U pip setuptools 
        python3 -m pip install ansible==2.7.4
        python3 -m pip install --ignore-installed https://github.com/galaxyproject/bioblend/archive/refs/tags/v0.15.0.zip pytest


    - name: Display pip python and ansible settings
      run: |
        which python
        python --version
        which python3
        python3 --version
        which pip3
        pip3 --version
        ansible --version
        pip show pytest
        pip show bioblend

    - uses: actions/checkout@v2

    - name: install ansible roles
      run: |
        ansible-galaxy install -r requirements_roles.yml -p roles

    - name: ansible installs galaxy
      run: |
        sudo apt-get update -y
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
        sudo apt-get --purge remove nginx*
        ansible-playbook -i inventory_files/galaxy-kickstart --extra-vars RUNNER_ALLOW_RUNASROOT="1" galaxy.yml

    - name: Sleep for 10 seconds
      run: |
        echo "waiting 10 sec" && sleep 10
            
    - name: restart galaxy services with supervisorctl
      run: |
        sudo supervisorctl restart galaxy:

    - name: Sleep for 10 seconds
      run: |
        echo "waiting 10 sec" && sleep 10

    - name: check Galaxy API is alive
      uses: mydea/action-wait-for-api@v1
      with:
        url: "http://localhost/api/version"
        timeout: 120

    - name: check supervisor services
      run: |
        sudo supervisorctl status
        curl http://localhost:80/api/version| grep version_major || true

    - name: ansible installs galaxy tools
      run: |
        ansible-playbook -i inventory_files/galaxy-kickstart --extra-vars RUNNER_ALLOW_RUNASROOT="1" galaxy_tool_install.yml

    - name: run basic tests
      run: |
        sudo supervisorctl status
        curl http://localhost:80/api/version| grep version_major
        echo "\ntest ftp transfer to proftpd server\n"
        date > date.txt && curl --fail -T date.txt ftp://127.0.0.1:21 --user $GALAXY_USER:$GALAXY_USER_PASSWD
      
    - name: Bioblend tests
      run: |
        cd /opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/bioblend/_tests/
        bioblend-galaxy-tests --color=yes -v TestGalaxyHistories.py TestGalaxyTools.py --no-summary || true

