name: Ansible Testing
on: [push, pull_request]
jobs:
  test 18.04:
    name: Ansible - Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Remove PostgreSQL on VM
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo apt-get --purge remove postgresql
        dpkg -l | grep postgres
        sudo apt-get --purge remove pgdg-keyring postgresql*
        sudo rm -rf /var/lib/postgresql/  # directory data postgresql
        sudo rm -rf /var/log/postgresql/  # directory log postgresql
        sudo rm -rf /etc/postgresql/  # directory base postgresql
        sudo deluser postgres
        sudo apt-get update -y

    - uses: actions/checkout@v2
    
    - name: Ansible deploy
      run: |
        sudo apt-get update -y
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
        ./test.sh

  test 16.04:
    name: Ansible - Ubuntu 16.04
    runs-on: ubuntu-16.04
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Remove PostgreSQL on VM
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo apt-get --purge remove postgresql
        dpkg -l | grep postgres
        sudo apt-get --purge remove pgdg-keyring postgresql*
        sudo rm -rf /var/lib/postgresql/  # directory data postgresql
        sudo rm -rf /var/log/postgresql/  # directory log postgresql
        sudo rm -rf /etc/postgresql/  # directory base postgresql
        sudo deluser postgres
        sudo apt-get update -y

    - uses: actions/checkout@v2
    
    - name: Ansible deploy
      run: |
        sudo apt-get update -y
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
        ./test.sh
