name: Ansible Testing
on: [push, pull_request]
jobs:
  test:
    name: Ansible
    runs-on: ubuntu-16.04



    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Remove PostgreSQL on VM
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo apt-get --purge remove postgresql
        dpkg -l | grep postgres
        sudo apt-get --purge remove pgdg-keyring postgresql*
        sudo rm -rf /var/lib/postgresql/  # directory data postgresql
        sudo rm -rf /var/log/postgresql/  # directory log postgresql
        sudo rm -rf /etc/postgresql/  # directory base postgresql
        sudo deluser postgres

    - uses: actions/checkout@v2



#    - name: Create scheduler user
#      run: |
#        sudo -u postgres psql --command="CREATE USER scheduler PASSWORD 'somestrong'" --command="\du"




#    - name: reconfigure
#      run: sudo dpkg-reconfigure --frontend=noninteractive tzdata
#
#    - name: Install Postgresql Packages
#      run: sudo apt-get install postgresql-10 postgresql-client-10 postgresql-plpython-10 postgresql-server-dev-10 virtualenv
#
#    - name: Start Postgresql
#      run: sudo service postgresql stop
#
    
    - name: Ansible deploy
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo -s
        whoami
        pwd
        sudo apt update -y
        sudo bash ./test.sh
