name: Ansible Testing
on: [push, pull_request]
jobs:
  test:
    name: Ansible
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - uses: actions/checkout@v2
    - name: Ansible deploy
      run: 'sudo ./test.sh'
