name: Ansible Testing
on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    env:
      GALAXY_USER: admin@galaxy.org
      GALAXY_USER_PASSWD: artbio2020
    
    steps:
    - name: Remove PostgreSQL on VM
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        sudo apt-get --purge remove postgresql
        dpkg -l | grep postgres
        sudo apt-get --purge remove pgdg-keyring postgresql*
        sudo rm -rf /var/lib/postgresql/  # directory data postgresql
        sudo rm -rf /var/log/postgresql/  # directory log postgresql
        sudo rm -rf /etc/postgresql/  # directory base postgresql
        sudo deluser postgres
        sudo apt-get update -y

    - name: Set up Python 3.7 in ubuntu 18.04
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
      if: matrix.os == 'ubuntu-18.04'
    
    - name: Set up pip and ansible in ubuntu 18.04
      run: |
        python3 -m pip install -U pip setuptools 
        python3 -m pip install ansible==2.7.4
        python3 -m pip install --ignore-installed https://github.com/galaxyproject/bioblend/archive/refs/tags/v0.15.0.zip pytest
      if: matrix.os == 'ubuntu-18.04'

    - name: Set up pip and ansible in ubuntu 16.04
      run: |
        sudo apt install -y python python-dev python-pip python-virtualenv
        python -m pip install -U 'pip<20.0.0'
        python -m pip install ansible==2.7.4
      if: matrix.os == 'ubuntu-16.04'
    
    - name: Display pip python and ansible settings
      run: |
        which python
        python --version
        which python3
        python3 --version
        ansible --version
        pip show pytest
        pip show bioblend

    - uses: actions/checkout@v2

    - name: install ansible roles
      run: |
        ansible-galaxy install -r requirements_roles.yml -p roles
        pwd

    - name: ansible installs galaxy
      run: |
        sudo apt-get update -y
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
        ansible-playbook -i inventory_files/galaxy-kickstart --extra-vars RUNNER_ALLOW_RUNASROOT="1" galaxy.yml

    - name: ansible installs galaxy tools
      run: |
        ansible-playbook -i inventory_files/galaxy-kickstart --extra-vars RUNNER_ALLOW_RUNASROOT="1" galaxy_tool_install.yml

    - name: run basic tests
      run: |
        sudo supervisorctl status
        curl http://localhost:80/api/version| grep version_major
        echo "\ntest ftp transfer to proftpd server\n"
        date > date.txt && curl --fail -T date.txt ftp://127.0.0.1:21 --user $GALAXY_USER:$GALAXY_USER_PASSWD

    - name: Bioblend tests
      run: |
        ./test.sh
      if: matrix.os == 'ubuntu-18.04'
