- name: Create/invoke script virtualenv for data managers
  pip: name={{ item }} virtualenv={{ galaxy_venv_dir }} virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the data manager script
  copy: src=galaxy_data_managers.py dest={{ galaxy_server_dir }}

- name: Copy data manager list file
  copy: src={{ galaxy_data_managers }} dest={{ galaxy_server_dir }}

- name: Run data managers
  command: chdir={{ galaxy_server_dir }} {{ galaxy_venv_dir }}/bin/python galaxy_data_managers.py -d {{ galaxy_data_managers }} -a {{ galaxy_admin_api_key }} -g localhost
