- name: get_supervisor_status
  shell: "supervisorctl status"
  register: galaxylogs
  ignore_errors: yes

- debug: var=supervisor_status

- name: get_supervisor_config
  shell: "cat /etc/supervisor/conf.d/galaxy.conf"
  register: supervisor_config
  ignore_errors: yes

- debug: var=supervisor_config

- name: get_galaxy_supervisor_logs
  shell: "tail -n 200 /var/log/supervisor/galaxy*"
  register: galaxy_supervisor_logs
  ignore_errors: yes

- debug: var=get_galaxy_supervisor_logs

- name: get_galaxy_logs
  shell: "tail -n 200 /home/galaxy/galaxy/*.log"
  register: galaxy_logs
  ignore_errors: yes

- debug: var=galaxy_logs
